# Site settings
email: lalibrairie.teebo@spamgourmet.com
safe: true
permalink: /:categories/:title
# Build settings
theme: jekyll-theme-slate
markdown: kramdown

defaults:
  -
    scope:
      path: "categories" 
    values:
      layout: "categoryPage"
  -
    scope:
      path: "_posts" 
    values:
      layout: "default"
  -
    scope:
      path: "_posts/exercices" 
    values:
      category: "exercice"
  -
    scope:
      path: "_posts/nouvelles" 
    values:
      category: "nouvelle"
  -
    scope:
      path: "_posts/romans" 
    values:
      category: "roman"
  -
    scope:
      path: "_posts/vagabondages" 
    values:
      category: "vagabondage"
